apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../kubernetes-manifests   # reuse your current base
patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: frontend
