apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - userassetsservice.yaml
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: frontend
      spec:
        template:
          spec:
            containers:
            - name: server
              env:
              - name: USER_ASSETS_SERVICE_ADDR
                value: "userassetsservice:8001"
